@echo off
echo Starting all preference engines...
echo.
echo Starting P05_ppk...
start "" /min cmd /c "X:\Models\P05_ppk\START.bat"
echo Starting P06_river...
start "" /min cmd /c "X:\Models\P06_river\START.bat"
echo Starting P07_markovify...
start "" /min cmd /c "X:\Models\P07_markovify\START.bat"
echo.
echo Active engines started.
pause
