@echo off
echo Starting all preference engines...
echo.
echo Starting preference-engine-ppk...
start "" /min cmd /c "X:\Models\preference-engine-ppk\START.bat"
echo Starting preference-engine-river...
start "" /min cmd /c "X:\Models\preference-engine-river\START.bat"
echo Starting preference-engine-markovify...
start "" /min cmd /c "X:\Models\preference-engine-markovify\START.bat"
echo.
echo Active engines started.
pause
