"""
renormalize_ids.py — bring every station's ID into per-lane sequence form.

Run from BACKSIDE/STATIONS/. Walks `stations/NN_*/`, derives `ST-LANE-NNN` per
lane (NNN counts within the lane in folder-number order), rewrites:

  - each station.yml's `station_id:`, `lane:`, and next-pass references
  - the top-level stations_registry.yml (regenerated from station.yml truth)

It also applies a couple of hardcoded LOGICAL fixes:

  - `7qs` lane is renamed to `sevenq` (parallel with ROUTE, CONV, CLAIM, etc.)
  - NLI substrate stations are unchained (next.pass → ST-TBD-000); they're
    parallel primitives, not a pipeline.
  - 11_7q_evidence's next.pass is wired to ST-GRAPH-001 (per David's spine:
    SEVENQ -> GRAPH -> PUB).

Idempotent: re-running produces the same result.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATIONS_DIR = ROOT / "stations"
REGISTRY = ROOT / "stations_registry.yml"

# Lane renames: old lane (lowercase, as written in station.yml) -> new lane.
LANE_RENAME = {
    "7qs": "sevenq",
}

# Logical next.pass overrides after renumbering. Folder name -> ST-LANE-NNN to point at.
NEXT_OVERRIDE = {
    "11_7q_evidence":  "ST-GRAPH-001",
    "03_nli_strong":   "ST-TBD-000",
    "04_nli_claim":    "ST-TBD-000",
    "05_nli_alt":      "ST-TBD-000",
}


def parse_station_yml(text: str) -> dict:
    """Light parser — just pulls the fields we care about. Avoids pyyaml dep."""
    out = {}
    for line in text.splitlines():
        m = re.match(r"^(station_id|name|lane|status):\s*(.+?)\s*$", line)
        if m:
            out[m.group(1)] = m.group(2)
        m = re.match(r"^  (primary|fallback|provider):\s*(.+?)\s*$", line)
        if m:
            # crude — only captures the first occurrence (model.primary etc.)
            key = m.group(1) + "_field"
            if key not in out:
                out[key] = m.group(2)
    return out


def collect_lane_assignments() -> tuple[dict, dict]:
    """
    Walk stations/NN_* in folder-number order. Build:
      - folder_name -> new_station_id
      - old_station_id -> new_station_id (for rewriting next.pass refs)
    """
    folders = sorted(d for d in STATIONS_DIR.iterdir()
                     if d.is_dir() and not d.name.startswith("_") and re.match(r"^\d{2}_", d.name))

    per_lane_counter: dict[str, int] = {}
    folder_to_new_id: dict[str, str] = {}
    old_to_new_id: dict[str, str] = {}

    for folder in folders:
        yml = folder / "station.yml"
        if not yml.exists():
            print(f"WARN: no station.yml in {folder.name}", file=sys.stderr)
            continue
        fields = parse_station_yml(yml.read_text(encoding="utf-8"))
        old_id = fields.get("station_id", "")
        old_lane = fields.get("lane", "misc").lower()
        new_lane = LANE_RENAME.get(old_lane, old_lane)

        per_lane_counter[new_lane] = per_lane_counter.get(new_lane, 0) + 1
        nnn = f"{per_lane_counter[new_lane]:03d}"
        new_id = f"ST-{new_lane.upper()}-{nnn}"

        folder_to_new_id[folder.name] = new_id
        if old_id:
            old_to_new_id[old_id] = new_id

    return folder_to_new_id, old_to_new_id


def rewrite_station_yml(folder: Path, new_id: str, new_lane: str,
                        old_to_new: dict[str, str]) -> None:
    yml = folder / "station.yml"
    text = yml.read_text(encoding="utf-8")

    # 1. station_id line
    text = re.sub(r"^station_id:\s*\S+", f"station_id: {new_id}",
                  text, count=1, flags=re.MULTILINE)
    # 2. lane line
    text = re.sub(r"^lane:\s*\S+", f"lane: {new_lane}",
                  text, count=1, flags=re.MULTILINE)
    # 3. logical next.pass override
    if folder.name in NEXT_OVERRIDE:
        target = NEXT_OVERRIDE[folder.name]
        # rewrite anything in the `pass:` list to the single override
        text = re.sub(
            r"(next:\s*\n\s+pass:\s*\n)(\s+- \S+\s*\n)+",
            rf"\1    - {target}\n",
            text,
            count=1,
        )
    # 4. translate any old ST-XXX-NNN refs anywhere
    for old, new in old_to_new.items():
        if old == new:
            continue
        text = re.sub(rf"\b{re.escape(old)}\b", new, text)

    yml.write_text(text, encoding="utf-8")


def regenerate_registry(folder_to_new_id: dict[str, str]) -> None:
    """Rebuild stations_registry.yml from station.yml truth."""
    lines = [
        "version: 1",
        "# Single source of truth for which stations exist, what they wrap, and how they wire.",
        "# Mirrors MODELS/model_registry.yml. Regenerated by _tools/renormalize_ids.py.",
        "stations:",
    ]
    for folder_name in sorted(folder_to_new_id.keys()):
        new_id = folder_to_new_id[folder_name]
        folder = STATIONS_DIR / folder_name
        yml = folder / "station.yml"
        text = yml.read_text(encoding="utf-8")
        fields = parse_station_yml(text)

        # Pull more fields with focused regex.
        def grab(field: str, default: str = "") -> str:
            m = re.search(rf"^  {field}:\s+(\S.*?)\s*$", text, re.MULTILINE)
            return m.group(1).strip() if m else default

        name = fields.get("name", folder_name)
        lane = fields.get("lane", "misc")
        status = fields.get("status", "draft")
        model_primary = grab("primary", "M-TBD-000")
        provider = grab("provider", "local_wrapper")

        # next.pass — first entry only
        np_match = re.search(r"next:\s*\n\s+pass:\s*\n\s+- (\S+)", text)
        next_pass = np_match.group(1) if np_match else "ST-TBD-000"

        lines.extend([
            f"",
            f"  - id: {new_id}",
            f"    name: {name}",
            f"    lane: {lane}",
            f"    status: {status}",
            f"    folder: stations/{folder_name}",
            f"    model: {model_primary}",
            f"    provider: {provider}",
            f"    inputs: [source.md]",
            f"    outputs: [result.json, result.md]",
            f"    next: [{next_pass}]",
        ])

    REGISTRY.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    folder_to_new_id, old_to_new = collect_lane_assignments()

    print("=== ID remap ===")
    for folder, new_id in folder_to_new_id.items():
        print(f"  {folder:<24} -> {new_id}")

    print("\n=== Rewriting station.yml files ===")
    for folder_name, new_id in folder_to_new_id.items():
        folder = STATIONS_DIR / folder_name
        new_lane = new_id.split("-")[1].lower()
        rewrite_station_yml(folder, new_id, new_lane, old_to_new)
        print(f"  {folder_name:<24} {new_id}  lane={new_lane}")

    print("\n=== Regenerating registry ===")
    regenerate_registry(folder_to_new_id)
    print(f"  wrote {REGISTRY}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
