"""
registry_rebuilder.py — atomically rebuild stations_registry.yml from
every stations/*/station.yml.

This is the ONLY legal writer of stations_registry.yml. No other script
should append to it directly. new_station.py creates folders; this
rebuilds the registry from those folders.

Concurrency safety:
- A .lock file blocks parallel rebuilds.
- Output is written to a .tmp then atomically replaced.
- Prior registry is backed up to _registry_backups/.

Duplicate station IDs are logged as warnings but still written — the
rebuilder reports ground truth; humans resolve conflicts.

Usage:
    python registry_rebuilder.py
    python registry_rebuilder.py --dry-run
"""

from __future__ import annotations

import argparse
import shutil
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(2)


ROOT = Path(__file__).resolve().parent
STATIONS_DIR = ROOT / "stations"
REGISTRY = ROOT / "stations_registry.yml"
LOCK = ROOT / "stations_registry.lock"
BACKUP_DIR = ROOT / "_registry_backups"


def collect_stations() -> tuple[list[dict], list[str]]:
    """Walk stations/, parse station.yml in each, return (entries, skipped_reasons)."""
    entries: list[dict] = []
    skipped: list[str] = []

    for station_dir in sorted(STATIONS_DIR.iterdir()):
        if not station_dir.is_dir():
            continue
        if station_dir.name.startswith("_"):
            continue
        yml_path = station_dir / "station.yml"
        if not yml_path.exists():
            skipped.append(f"{station_dir.name}: no station.yml")
            continue
        try:
            meta = yaml.safe_load(yml_path.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            skipped.append(f"{station_dir.name}: yaml error — {exc}")
            continue
        if not isinstance(meta, dict):
            skipped.append(f"{station_dir.name}: station.yml is not a mapping")
            continue
        sid = meta.get("station_id")
        if not sid or "{{" in str(sid):
            skipped.append(f"{station_dir.name}: missing or placeholder station_id")
            continue

        model_block = meta.get("model") or {}
        input_block = meta.get("input") or {}
        output_block = meta.get("output") or {}
        next_block = meta.get("next") or {}

        entries.append({
            "id": sid,
            "name": meta.get("name") or station_dir.name,
            "lane": meta.get("lane") or "misc",
            "status": meta.get("status") or "draft",
            "folder": f"stations/{station_dir.name}",
            "model": model_block.get("primary") or "M-TBD-000",
            "provider": model_block.get("provider") or "local_wrapper",
            "inputs": input_block.get("required_files") or ["source.md"],
            "outputs": output_block.get("produces") or ["result.json", "result.md"],
            "next": next_block.get("pass") or ["ST-TBD-000"],
        })

    return entries, skipped


def render_registry(entries: list[dict]) -> str:
    """Stable YAML rendering, lane-grouped then id-sorted within lane."""
    entries = sorted(entries, key=lambda e: (e["lane"], e["id"]))
    lines = [
        "version: 1",
        "# Auto-generated by registry_rebuilder.py — DO NOT EDIT BY HAND.",
        "# Source of truth: each folder's station.yml.",
        "# To add/change a station: edit (or create) the folder's station.yml, then re-run registry_rebuilder.py.",
        f"# Last rebuilt: {datetime.now().isoformat(timespec='seconds')}",
        "stations:",
    ]
    for e in entries:
        lines.append("")
        lines.append(f"  - id: {e['id']}")
        lines.append(f"    name: {e['name']}")
        lines.append(f"    lane: {e['lane']}")
        lines.append(f"    status: {e['status']}")
        lines.append(f"    folder: {e['folder']}")
        lines.append(f"    model: {e['model']}")
        lines.append(f"    provider: {e['provider']}")
        lines.append(f"    inputs: [{', '.join(map(str, e['inputs']))}]")
        lines.append(f"    outputs: [{', '.join(map(str, e['outputs']))}]")
        lines.append(f"    next: [{', '.join(map(str, e['next']))}]")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Rebuild stations_registry.yml from station.yml files.")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be written; don't touch the registry.")
    args = parser.parse_args()

    if LOCK.exists():
        print(f"ERROR: lock present at {LOCK}", file=sys.stderr)
        print("Another rebuild is in progress, or the lock is stale.", file=sys.stderr)
        print("If stale, delete it manually and re-run.", file=sys.stderr)
        return 2

    if not STATIONS_DIR.is_dir():
        print(f"ERROR: stations dir missing: {STATIONS_DIR}", file=sys.stderr)
        return 2

    if not args.dry_run:
        LOCK.write_text(f"rebuild_started={datetime.now().isoformat(timespec='seconds')}\npid={None}\n", encoding="utf-8")

    try:
        entries, skipped = collect_stations()

        # Dupe check
        id_counts = Counter(e["id"] for e in entries)
        dupes = {sid: c for sid, c in id_counts.items() if c > 1}

        new_content = render_registry(entries)

        if args.dry_run:
            print("--- DRY RUN ---")
            print(new_content)
        else:
            BACKUP_DIR.mkdir(exist_ok=True)
            if REGISTRY.exists():
                ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                shutil.copy2(REGISTRY, BACKUP_DIR / f"stations_registry_{ts}.yml.bak")
            tmp = REGISTRY.with_suffix(".yml.tmp")
            tmp.write_text(new_content, encoding="utf-8")
            tmp.replace(REGISTRY)

        lanes = Counter(e["lane"] for e in entries)
        print(f"Stations: {len(entries)}")
        print(f"Lanes:    {dict(sorted(lanes.items()))}")
        if skipped:
            print(f"Skipped {len(skipped)}:")
            for s in skipped:
                print(f"  - {s}")
        if dupes:
            print(f"DUPLICATE station_ids (resolve before status->active):")
            for sid, n in dupes.items():
                folders = [e["folder"] for e in entries if e["id"] == sid]
                print(f"  - {sid} ({n}x): {folders}")
            return 1
        return 0
    finally:
        LOCK.unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
